### ISSUE TITLE
关于riscv调试

### ISSUE THREAD

**Issue by mttbx** [vllogic/openocd_cmsis-dap_v2#1]
cmsis dap 也能用来调试riscv吗？ 使用的固件是ARMmbed/DAPLink吗？

**Comment by talpachen** [comment]
能用，但速度非常慢。
目前对非ARM芯片，建议使用FT2232此类接口芯片。
速度慢的原因与硬件、通讯协议无关，与openocd驱动层代码有关，当前开源组织对相关使用场景的优化非常差劲。

**Comment by mttbx** [comment]
谢谢您的回复！
